//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Squint {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class SquintProtocol {
        
        private byte protocolIDField;
        
        private byte versionField;
        
        private SquintProtocolProtocolMetaData protocolMetaDataField;
        
        private SquintProtocolIntent[] treatmentIntentsField;
        
        private SquintProtocolStructure[] structuresField;
        
        private SquintProtocolProtocolChecklist protocolChecklistField;
        
        private SquintProtocolComponent[] componentsField;
        
        private SquintProtocolConstraint[] constraintsField;
        
        /// <remarks/>
        public byte ProtocolID {
            get {
                return this.protocolIDField;
            }
            set {
                this.protocolIDField = value;
            }
        }
        
        /// <remarks/>
        public byte version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public SquintProtocolProtocolMetaData ProtocolMetaData {
            get {
                return this.protocolMetaDataField;
            }
            set {
                this.protocolMetaDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Intent", IsNullable=false)]
        public SquintProtocolIntent[] TreatmentIntents {
            get {
                return this.treatmentIntentsField;
            }
            set {
                this.treatmentIntentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Structure", IsNullable=false)]
        public SquintProtocolStructure[] Structures {
            get {
                return this.structuresField;
            }
            set {
                this.structuresField = value;
            }
        }
        
        /// <remarks/>
        public SquintProtocolProtocolChecklist ProtocolChecklist {
            get {
                return this.protocolChecklistField;
            }
            set {
                this.protocolChecklistField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Component", IsNullable=false)]
        public SquintProtocolComponent[] Components {
            get {
                return this.componentsField;
            }
            set {
                this.componentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Constraint", IsNullable=false)]
        public SquintProtocolConstraint[] Constraints {
            get {
                return this.constraintsField;
            }
            set {
                this.constraintsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolProtocolMetaData {
        
        private string protocolNameField;
        
        private ProtocolTypes protocolTypeField;
        
        private int numComponentsField;
        
        private string protocolDateField;
        
        private string authorField;
        
        private ApprovalLevels approvalStatusField;
        
        private TreatmentSites diseaseSiteField;
        
        private TreatmentCentres treatmentCentreField;
        
        public SquintProtocolProtocolMetaData() {
            this.approvalStatusField = ApprovalLevels.Unapproved;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProtocolName {
            get {
                return this.protocolNameField;
            }
            set {
                this.protocolNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ProtocolTypes ProtocolType {
            get {
                return this.protocolTypeField;
            }
            set {
                this.protocolTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int NumComponents {
            get {
                return this.numComponentsField;
            }
            set {
                this.numComponentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProtocolDate {
            get {
                return this.protocolDateField;
            }
            set {
                this.protocolDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ApprovalLevels.Unapproved)]
        public ApprovalLevels ApprovalStatus {
            get {
                return this.approvalStatusField;
            }
            set {
                this.approvalStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TreatmentSites DiseaseSite {
            get {
                return this.diseaseSiteField;
            }
            set {
                this.diseaseSiteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TreatmentCentres TreatmentCentre {
            get {
                return this.treatmentCentreField;
            }
            set {
                this.treatmentCentreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum ProtocolTypes {
        
        /// <remarks/>
        Unset,
        
        /// <remarks/>
        All,
        
        /// <remarks/>
        Clinical,
        
        /// <remarks/>
        Trial,
        
        /// <remarks/>
        Research,
        
        /// <remarks/>
        Development,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum ApprovalLevels {
        
        /// <remarks/>
        Unset,
        
        /// <remarks/>
        All,
        
        /// <remarks/>
        Unapproved,
        
        /// <remarks/>
        Reviewed,
        
        /// <remarks/>
        Approved,
        
        /// <remarks/>
        Retired,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum TreatmentSites {
        
        /// <remarks/>
        Unset,
        
        /// <remarks/>
        All,
        
        /// <remarks/>
        GU,
        
        /// <remarks/>
        GI,
        
        /// <remarks/>
        Lung,
        
        /// <remarks/>
        HN,
        
        /// <remarks/>
        CNS,
        
        /// <remarks/>
        Sarcoma,
        
        /// <remarks/>
        Breast,
        
        /// <remarks/>
        Lymphoma,
        
        /// <remarks/>
        Palliative,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum TreatmentCentres {
        
        /// <remarks/>
        Unset,
        
        /// <remarks/>
        All,
        
        /// <remarks/>
        Provincial,
        
        /// <remarks/>
        CN,
        
        /// <remarks/>
        VCC,
        
        /// <remarks/>
        VIC,
        
        /// <remarks/>
        AC,
        
        /// <remarks/>
        FVCC,
        
        /// <remarks/>
        CSI,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolIntent {
        
        private TreatmentIntents idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TreatmentIntents Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum TreatmentIntents {
        
        /// <remarks/>
        Unset,
        
        /// <remarks/>
        Curative,
        
        /// <remarks/>
        Adjuvant,
        
        /// <remarks/>
        NeoAdjuvant,
        
        /// <remarks/>
        Palliative,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolStructure {
        
        private SquintProtocolStructureStructureChecklist structureChecklistField;
        
        private SquintProtocolStructureEclipseId[] eclipseAliasesField;
        
        private string labelField;
        
        private string protocolStructureNameField;
        
        /// <remarks/>
        public SquintProtocolStructureStructureChecklist StructureChecklist {
            get {
                return this.structureChecklistField;
            }
            set {
                this.structureChecklistField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("EclipseId", IsNullable=false)]
        public SquintProtocolStructureEclipseId[] EclipseAliases {
            get {
                return this.eclipseAliasesField;
            }
            set {
                this.eclipseAliasesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProtocolStructureName {
            get {
                return this.protocolStructureNameField;
            }
            set {
                this.protocolStructureNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolStructureStructureChecklist {
        
        private SquintProtocolStructureStructureChecklistPointContourCheck pointContourCheckField;
        
        /// <remarks/>
        public SquintProtocolStructureStructureChecklistPointContourCheck PointContourCheck {
            get {
                return this.pointContourCheckField;
            }
            set {
                this.pointContourCheckField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolStructureStructureChecklistPointContourCheck {
        
        private double thresholdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Threshold {
            get {
                return this.thresholdField;
            }
            set {
                this.thresholdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolStructureEclipseId {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolProtocolChecklist {
        
        private SquintProtocolProtocolChecklistArtifact[] artifactsField;
        
        private SquintProtocolProtocolChecklistSupports supportsField;
        
        private SquintProtocolProtocolChecklistCalculation calculationField;
        
        private SquintProtocolProtocolChecklistSimulation simulationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Artifact", IsNullable=false)]
        public SquintProtocolProtocolChecklistArtifact[] Artifacts {
            get {
                return this.artifactsField;
            }
            set {
                this.artifactsField = value;
            }
        }
        
        /// <remarks/>
        public SquintProtocolProtocolChecklistSupports Supports {
            get {
                return this.supportsField;
            }
            set {
                this.supportsField = value;
            }
        }
        
        /// <remarks/>
        public SquintProtocolProtocolChecklistCalculation Calculation {
            get {
                return this.calculationField;
            }
            set {
                this.calculationField = value;
            }
        }
        
        /// <remarks/>
        public SquintProtocolProtocolChecklistSimulation Simulation {
            get {
                return this.simulationField;
            }
            set {
                this.simulationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolProtocolChecklistArtifact {
        
        private double huField;
        
        private double toleranceHUField;
        
        private string protocolStructureNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double HU {
            get {
                return this.huField;
            }
            set {
                this.huField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double ToleranceHU {
            get {
                return this.toleranceHUField;
            }
            set {
                this.toleranceHUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProtocolStructureName {
            get {
                return this.protocolStructureNameField;
            }
            set {
                this.protocolStructureNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolProtocolChecklistSupports {
        
        private double couchSurfaceField;
        
        private double couchInteriorField;
        
        private ParameterOptions indicationField;
        
        public SquintProtocolProtocolChecklistSupports() {
            this.couchSurfaceField = -300D;
            this.couchInteriorField = 0D;
            this.indicationField = ParameterOptions.Optional;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(-300D)]
        public double CouchSurface {
            get {
                return this.couchSurfaceField;
            }
            set {
                this.couchSurfaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double CouchInterior {
            get {
                return this.couchInteriorField;
            }
            set {
                this.couchInteriorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ParameterOptions.Optional)]
        public ParameterOptions Indication {
            get {
                return this.indicationField;
            }
            set {
                this.indicationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum ParameterOptions {
        
        /// <remarks/>
        Unset,
        
        /// <remarks/>
        Optional,
        
        /// <remarks/>
        Required,
        
        /// <remarks/>
        None,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolProtocolChecklistCalculation {
        
        private AlgorithmVolumeDoseTypes algorithmField;
        
        private bool algorithmFieldSpecified;
        
        private double algorithmResolutionField;
        
        private bool algorithmResolutionFieldSpecified;
        
        private bool heterogeneityOnField;
        
        private bool heterogeneityOnFieldSpecified;
        
        private string vMATAirCavityCorrectionField;
        
        private string iMRTAirCavityCorrectionField;
        
        private FieldNormalizationTypes fieldNormalizationModeField;
        
        private bool fieldNormalizationModeFieldSpecified;
        
        private AlgorithmVMATOptimizationTypes vMATOptimizationAlgorithmField;
        
        private AlgorithmIMRTOptimizationTypes iMRTOptimizationAlgorithmField;
        
        public SquintProtocolProtocolChecklistCalculation() {
            this.vMATOptimizationAlgorithmField = AlgorithmVMATOptimizationTypes.Unset;
            this.iMRTOptimizationAlgorithmField = AlgorithmIMRTOptimizationTypes.Unset;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AlgorithmVolumeDoseTypes Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AlgorithmSpecified {
            get {
                return this.algorithmFieldSpecified;
            }
            set {
                this.algorithmFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double AlgorithmResolution {
            get {
                return this.algorithmResolutionField;
            }
            set {
                this.algorithmResolutionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AlgorithmResolutionSpecified {
            get {
                return this.algorithmResolutionFieldSpecified;
            }
            set {
                this.algorithmResolutionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool HeterogeneityOn {
            get {
                return this.heterogeneityOnField;
            }
            set {
                this.heterogeneityOnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HeterogeneityOnSpecified {
            get {
                return this.heterogeneityOnFieldSpecified;
            }
            set {
                this.heterogeneityOnFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VMATAirCavityCorrection {
            get {
                return this.vMATAirCavityCorrectionField;
            }
            set {
                this.vMATAirCavityCorrectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IMRTAirCavityCorrection {
            get {
                return this.iMRTAirCavityCorrectionField;
            }
            set {
                this.iMRTAirCavityCorrectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public FieldNormalizationTypes FieldNormalizationMode {
            get {
                return this.fieldNormalizationModeField;
            }
            set {
                this.fieldNormalizationModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FieldNormalizationModeSpecified {
            get {
                return this.fieldNormalizationModeFieldSpecified;
            }
            set {
                this.fieldNormalizationModeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(AlgorithmVMATOptimizationTypes.Unset)]
        public AlgorithmVMATOptimizationTypes VMATOptimizationAlgorithm {
            get {
                return this.vMATOptimizationAlgorithmField;
            }
            set {
                this.vMATOptimizationAlgorithmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(AlgorithmIMRTOptimizationTypes.Unset)]
        public AlgorithmIMRTOptimizationTypes IMRTOptimizationAlgorithm {
            get {
                return this.iMRTOptimizationAlgorithmField;
            }
            set {
                this.iMRTOptimizationAlgorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum AlgorithmVolumeDoseTypes {
        
        /// <remarks/>
        Unset,
        
        /// <remarks/>
        AAA_11031,
        
        /// <remarks/>
        AAA_13623,
        
        /// <remarks/>
        AAA_15606,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum FieldNormalizationTypes {
        
        /// <remarks/>
        Unset,
        
        /// <remarks/>
        ISO,
        
        /// <remarks/>
        CAX,
        
        /// <remarks/>
        field,
        
        /// <remarks/>
        None,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum AlgorithmVMATOptimizationTypes {
        
        /// <remarks/>
        Unset,
        
        /// <remarks/>
        PRO_13623,
        
        /// <remarks/>
        PO_13623,
        
        /// <remarks/>
        PO_15606,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum AlgorithmIMRTOptimizationTypes {
        
        /// <remarks/>
        Unset,
        
        /// <remarks/>
        PRO_13623,
        
        /// <remarks/>
        PO_13623,
        
        /// <remarks/>
        PO_15606,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolProtocolChecklistSimulation {
        
        private SquintProtocolProtocolChecklistSimulationCTDeviceId[] cTDeviceIdsField;
        
        private double sliceSpacingField;
        
        public SquintProtocolProtocolChecklistSimulation() {
            this.sliceSpacingField = double.NaN;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CTDeviceId", IsNullable=false)]
        public SquintProtocolProtocolChecklistSimulationCTDeviceId[] CTDeviceIds {
            get {
                return this.cTDeviceIdsField;
            }
            set {
                this.cTDeviceIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(double.NaN)]
        public double SliceSpacing {
            get {
                return this.sliceSpacingField;
            }
            set {
                this.sliceSpacingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolProtocolChecklistSimulationCTDeviceId {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolComponent {
        
        private SquintProtocolComponentPrescription prescriptionField;
        
        private SquintProtocolComponentImagingProtocol[] imagingProtocolsField;
        
        private SquintProtocolComponentConstituent[] constituentsField;
        
        private SquintProtocolComponentBeams beamsField;
        
        private string componentNameField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private ComponentTypes typeField;
        
        private int numFractionsField;
        
        private bool numFractionsFieldSpecified;
        
        private double referenceDoseField;
        
        private bool referenceDoseFieldSpecified;
        
        /// <remarks/>
        public SquintProtocolComponentPrescription Prescription {
            get {
                return this.prescriptionField;
            }
            set {
                this.prescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ImagingProtocol", IsNullable=false)]
        public SquintProtocolComponentImagingProtocol[] ImagingProtocols {
            get {
                return this.imagingProtocolsField;
            }
            set {
                this.imagingProtocolsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Constituent", IsNullable=false)]
        public SquintProtocolComponentConstituent[] Constituents {
            get {
                return this.constituentsField;
            }
            set {
                this.constituentsField = value;
            }
        }
        
        /// <remarks/>
        public SquintProtocolComponentBeams Beams {
            get {
                return this.beamsField;
            }
            set {
                this.beamsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ComponentName {
            get {
                return this.componentNameField;
            }
            set {
                this.componentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ComponentTypes Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int NumFractions {
            get {
                return this.numFractionsField;
            }
            set {
                this.numFractionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumFractionsSpecified {
            get {
                return this.numFractionsFieldSpecified;
            }
            set {
                this.numFractionsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double ReferenceDose {
            get {
                return this.referenceDoseField;
            }
            set {
                this.referenceDoseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReferenceDoseSpecified {
            get {
                return this.referenceDoseFieldSpecified;
            }
            set {
                this.referenceDoseFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolComponentPrescription {
        
        private int numFractionsField;
        
        private double referenceDoseField;
        
        private double pNVMinField;
        
        private bool pNVMinFieldSpecified;
        
        private double pNVMaxField;
        
        private bool pNVMaxFieldSpecified;
        
        private double prescribedPercentageField;
        
        private bool prescribedPercentageFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int NumFractions {
            get {
                return this.numFractionsField;
            }
            set {
                this.numFractionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double ReferenceDose {
            get {
                return this.referenceDoseField;
            }
            set {
                this.referenceDoseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double PNVMin {
            get {
                return this.pNVMinField;
            }
            set {
                this.pNVMinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PNVMinSpecified {
            get {
                return this.pNVMinFieldSpecified;
            }
            set {
                this.pNVMinFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double PNVMax {
            get {
                return this.pNVMaxField;
            }
            set {
                this.pNVMaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PNVMaxSpecified {
            get {
                return this.pNVMaxFieldSpecified;
            }
            set {
                this.pNVMaxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double PrescribedPercentage {
            get {
                return this.prescribedPercentageField;
            }
            set {
                this.prescribedPercentageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrescribedPercentageSpecified {
            get {
                return this.prescribedPercentageFieldSpecified;
            }
            set {
                this.prescribedPercentageFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolComponentImagingProtocol {
        
        private ImagingProtocolTypes idField;
        
        private string imagingProtocolDisplayNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ImagingProtocolTypes Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ImagingProtocolDisplayName {
            get {
                return this.imagingProtocolDisplayNameField;
            }
            set {
                this.imagingProtocolDisplayNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum ImagingProtocolTypes {
        
        /// <remarks/>
        Unset,
        
        /// <remarks/>
        kV,
        
        /// <remarks/>
        kV_2D,
        
        /// <remarks/>
        Bolus,
        
        /// <remarks/>
        PreCBCT,
        
        /// <remarks/>
        PostCBCT,
        
        /// <remarks/>
        MidTxCBCT,
        
        /// <remarks/>
        Home,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolComponentConstituent {
        
        private string componentNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ComponentName {
            get {
                return this.componentNameField;
            }
            set {
                this.componentNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolComponentBeams {
        
        private SquintProtocolComponentBeamsBeam[] beamField;
        
        private int minBeamsField;
        
        private double minColOffsetField;
        
        private int maxBeamsField;
        
        private int numIsoField;
        
        public SquintProtocolComponentBeams() {
            this.minBeamsField = -1;
            this.minColOffsetField = double.NaN;
            this.maxBeamsField = -1;
            this.numIsoField = 1;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Beam")]
        public SquintProtocolComponentBeamsBeam[] Beam {
            get {
                return this.beamField;
            }
            set {
                this.beamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int MinBeams {
            get {
                return this.minBeamsField;
            }
            set {
                this.minBeamsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(double.NaN)]
        public double MinColOffset {
            get {
                return this.minColOffsetField;
            }
            set {
                this.minColOffsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int MaxBeams {
            get {
                return this.maxBeamsField;
            }
            set {
                this.maxBeamsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1)]
        public int NumIso {
            get {
                return this.numIsoField;
            }
            set {
                this.numIsoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolComponentBeamsBeam {
        
        private SquintProtocolComponentBeamsBeamEclipseId[] eclipseAliasesField;
        
        private SquintProtocolComponentBeamsBeamBolus[] bolusDefinitionsField;
        
        private SquintProtocolComponentBeamsBeamGeometry[] validGeometriesField;
        
        private SquintProtocolComponentBeamsBeamEnergy[] validEnergiesField;
        
        private string protocolBeamNameField;
        
        private FieldTechniqueType techniqueField;
        
        private double minMUWarningField;
        
        private double maxMUWarningField;
        
        private string toleranceTableField;
        
        private double minColRotationField;
        
        private double couchRotationField;
        
        private double minXField;
        
        private double maxXField;
        
        private double minYField;
        
        private double maxYField;
        
        private ParameterOptions jawTracking_IndicationField;
        
        private double maxColRotationField;
        
        public SquintProtocolComponentBeamsBeam() {
            this.minMUWarningField = double.NaN;
            this.maxMUWarningField = double.NaN;
            this.minColRotationField = double.NaN;
            this.couchRotationField = double.NaN;
            this.minXField = double.NaN;
            this.maxXField = double.NaN;
            this.minYField = double.NaN;
            this.maxYField = double.NaN;
            this.jawTracking_IndicationField = ParameterOptions.Optional;
            this.maxColRotationField = double.NaN;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("EclipseId", IsNullable=false)]
        public SquintProtocolComponentBeamsBeamEclipseId[] EclipseAliases {
            get {
                return this.eclipseAliasesField;
            }
            set {
                this.eclipseAliasesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Bolus", IsNullable=false)]
        public SquintProtocolComponentBeamsBeamBolus[] BolusDefinitions {
            get {
                return this.bolusDefinitionsField;
            }
            set {
                this.bolusDefinitionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Geometry", IsNullable=false)]
        public SquintProtocolComponentBeamsBeamGeometry[] ValidGeometries {
            get {
                return this.validGeometriesField;
            }
            set {
                this.validGeometriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Energy", IsNullable=false)]
        public SquintProtocolComponentBeamsBeamEnergy[] ValidEnergies {
            get {
                return this.validEnergiesField;
            }
            set {
                this.validEnergiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProtocolBeamName {
            get {
                return this.protocolBeamNameField;
            }
            set {
                this.protocolBeamNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public FieldTechniqueType Technique {
            get {
                return this.techniqueField;
            }
            set {
                this.techniqueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(double.NaN)]
        public double MinMUWarning {
            get {
                return this.minMUWarningField;
            }
            set {
                this.minMUWarningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(double.NaN)]
        public double MaxMUWarning {
            get {
                return this.maxMUWarningField;
            }
            set {
                this.maxMUWarningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ToleranceTable {
            get {
                return this.toleranceTableField;
            }
            set {
                this.toleranceTableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(double.NaN)]
        public double MinColRotation {
            get {
                return this.minColRotationField;
            }
            set {
                this.minColRotationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(double.NaN)]
        public double CouchRotation {
            get {
                return this.couchRotationField;
            }
            set {
                this.couchRotationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(double.NaN)]
        public double MinX {
            get {
                return this.minXField;
            }
            set {
                this.minXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(double.NaN)]
        public double MaxX {
            get {
                return this.maxXField;
            }
            set {
                this.maxXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(double.NaN)]
        public double MinY {
            get {
                return this.minYField;
            }
            set {
                this.minYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(double.NaN)]
        public double MaxY {
            get {
                return this.maxYField;
            }
            set {
                this.maxYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ParameterOptions.Optional)]
        public ParameterOptions JawTracking_Indication {
            get {
                return this.jawTracking_IndicationField;
            }
            set {
                this.jawTracking_IndicationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(double.NaN)]
        public double MaxColRotation {
            get {
                return this.maxColRotationField;
            }
            set {
                this.maxColRotationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolComponentBeamsBeamEclipseId {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolComponentBeamsBeamBolus {
        
        private double huField;
        
        private double thicknessField;
        
        private ParameterOptions indicationField;
        
        private double toleranceHUField;
        
        private double toleranceThicknessField;
        
        public SquintProtocolComponentBeamsBeamBolus() {
            this.thicknessField = 0.5D;
            this.toleranceHUField = double.NaN;
            this.toleranceThicknessField = double.NaN;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double HU {
            get {
                return this.huField;
            }
            set {
                this.huField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0.5D)]
        public double Thickness {
            get {
                return this.thicknessField;
            }
            set {
                this.thicknessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ParameterOptions Indication {
            get {
                return this.indicationField;
            }
            set {
                this.indicationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(double.NaN)]
        public double ToleranceHU {
            get {
                return this.toleranceHUField;
            }
            set {
                this.toleranceHUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(double.NaN)]
        public double ToleranceThickness {
            get {
                return this.toleranceThicknessField;
            }
            set {
                this.toleranceThicknessField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolComponentBeamsBeamGeometry {
        
        private string geometryNameField;
        
        private double startAngleField;
        
        private double startAngleToleranceField;
        
        private double endAngleField;
        
        private double endAngleToleranceField;
        
        private TrajectoryTypes trajectoryField;
        
        public SquintProtocolComponentBeamsBeamGeometry() {
            this.startAngleToleranceField = double.NaN;
            this.endAngleToleranceField = double.NaN;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string GeometryName {
            get {
                return this.geometryNameField;
            }
            set {
                this.geometryNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double StartAngle {
            get {
                return this.startAngleField;
            }
            set {
                this.startAngleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(double.NaN)]
        public double StartAngleTolerance {
            get {
                return this.startAngleToleranceField;
            }
            set {
                this.startAngleToleranceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double EndAngle {
            get {
                return this.endAngleField;
            }
            set {
                this.endAngleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(double.NaN)]
        public double EndAngleTolerance {
            get {
                return this.endAngleToleranceField;
            }
            set {
                this.endAngleToleranceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TrajectoryTypes Trajectory {
            get {
                return this.trajectoryField;
            }
            set {
                this.trajectoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum TrajectoryTypes {
        
        /// <remarks/>
        Unset,
        
        /// <remarks/>
        Static,
        
        /// <remarks/>
        CW,
        
        /// <remarks/>
        CCW,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolComponentBeamsBeamEnergy {
        
        private Energies modeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Energies Mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum Energies {
        
        /// <remarks/>
        Unset,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6X")]
        Item6X,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10X")]
        Item10X,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("15X")]
        Item15X,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10XFFF")]
        Item10XFFF,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6XFFF")]
        Item6XFFF,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum FieldTechniqueType {
        
        /// <remarks/>
        Unset,
        
        /// <remarks/>
        BolusSetup,
        
        /// <remarks/>
        LL_kv,
        
        /// <remarks/>
        RL_kv,
        
        /// <remarks/>
        CBCT,
        
        /// <remarks/>
        Ant_kv,
        
        /// <remarks/>
        Post_kv,
        
        /// <remarks/>
        STATIC,
        
        /// <remarks/>
        ARC,
        
        /// <remarks/>
        Unload,
        
        /// <remarks/>
        Home,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum ComponentTypes {
        
        /// <remarks/>
        Unset,
        
        /// <remarks/>
        Phase,
        
        /// <remarks/>
        Sum,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolConstraint {
        
        private string componentNameField;
        
        private int componentIdField;
        
        private bool componentIdFieldSpecified;
        
        private string protocolStructureNameField;
        
        private ConstraintTypes constraintTypeField;
        
        private double constraintValueField;
        
        private UnitScale constraintUnitField;
        
        private ReferenceTypes referenceTypeField;
        
        private double majorViolationField;
        
        private double minorViolationField;
        
        private UnitScale referenceUnitField;
        
        private double stopField;
        
        private string descriptionField;
        
        private string dataTablePathField;
        
        private string referenceStructureNameField;
        
        public SquintProtocolConstraint() {
            this.minorViolationField = double.NaN;
            this.stopField = double.NaN;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ComponentName {
            get {
                return this.componentNameField;
            }
            set {
                this.componentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ComponentId {
            get {
                return this.componentIdField;
            }
            set {
                this.componentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ComponentIdSpecified {
            get {
                return this.componentIdFieldSpecified;
            }
            set {
                this.componentIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProtocolStructureName {
            get {
                return this.protocolStructureNameField;
            }
            set {
                this.protocolStructureNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ConstraintTypes ConstraintType {
            get {
                return this.constraintTypeField;
            }
            set {
                this.constraintTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double ConstraintValue {
            get {
                return this.constraintValueField;
            }
            set {
                this.constraintValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public UnitScale ConstraintUnit {
            get {
                return this.constraintUnitField;
            }
            set {
                this.constraintUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ReferenceTypes ReferenceType {
            get {
                return this.referenceTypeField;
            }
            set {
                this.referenceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double MajorViolation {
            get {
                return this.majorViolationField;
            }
            set {
                this.majorViolationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(double.NaN)]
        public double MinorViolation {
            get {
                return this.minorViolationField;
            }
            set {
                this.minorViolationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public UnitScale ReferenceUnit {
            get {
                return this.referenceUnitField;
            }
            set {
                this.referenceUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(double.NaN)]
        public double Stop {
            get {
                return this.stopField;
            }
            set {
                this.stopField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DataTablePath {
            get {
                return this.dataTablePathField;
            }
            set {
                this.dataTablePathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReferenceStructureName {
            get {
                return this.referenceStructureNameField;
            }
            set {
                this.referenceStructureNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum ConstraintTypes {
        
        /// <remarks/>
        Unset,
        
        /// <remarks/>
        D,
        
        /// <remarks/>
        V,
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        CV,
        
        /// <remarks/>
        CI,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum UnitScale {
        
        /// <remarks/>
        Unset,
        
        /// <remarks/>
        Relative,
        
        /// <remarks/>
        Absolute,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum ReferenceTypes {
        
        /// <remarks/>
        Unset,
        
        /// <remarks/>
        Upper,
        
        /// <remarks/>
        Lower,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class SquintConfiguration {
        
        private SquintConfigurationSite siteField;
        
        private SquintConfigurationDatabase[] databasesField;
        
        private SquintConfigurationPathDef[] beamGeometryDefinitionsField;
        
        private SquintConfigurationPathDef1[] structureCodesField;
        
        private SquintConfigurationPathDef2[] clinicalProtocolsField;
        
        private SquintConfigurationPathDef3[] squintProtocolsField;
        
        /// <remarks/>
        public SquintConfigurationSite Site {
            get {
                return this.siteField;
            }
            set {
                this.siteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Database", IsNullable=false)]
        public SquintConfigurationDatabase[] Databases {
            get {
                return this.databasesField;
            }
            set {
                this.databasesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("PathDef", IsNullable=false)]
        public SquintConfigurationPathDef[] BeamGeometryDefinitions {
            get {
                return this.beamGeometryDefinitionsField;
            }
            set {
                this.beamGeometryDefinitionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("PathDef", IsNullable=false)]
        public SquintConfigurationPathDef1[] StructureCodes {
            get {
                return this.structureCodesField;
            }
            set {
                this.structureCodesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("PathDef", IsNullable=false)]
        public SquintConfigurationPathDef2[] ClinicalProtocols {
            get {
                return this.clinicalProtocolsField;
            }
            set {
                this.clinicalProtocolsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("PathDef", IsNullable=false)]
        public SquintConfigurationPathDef3[] SquintProtocols {
            get {
                return this.squintProtocolsField;
            }
            set {
                this.squintProtocolsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintConfigurationSite {
        
        private string currentSiteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CurrentSite {
            get {
                return this.currentSiteField;
            }
            set {
                this.currentSiteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintConfigurationDatabase {
        
        private string siteField;
        
        private string displayNameField;
        
        private string databaseNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Site {
            get {
                return this.siteField;
            }
            set {
                this.siteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DatabaseName {
            get {
                return this.databaseNameField;
            }
            set {
                this.databaseNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintConfigurationPathDef {
        
        private string siteField;
        
        private string pathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Site {
            get {
                return this.siteField;
            }
            set {
                this.siteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintConfigurationPathDef1 {
        
        private string siteField;
        
        private string pathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Site {
            get {
                return this.siteField;
            }
            set {
                this.siteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintConfigurationPathDef2 {
        
        private string siteField;
        
        private string pathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Site {
            get {
                return this.siteField;
            }
            set {
                this.siteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintConfigurationPathDef3 {
        
        private string siteField;
        
        private string pathField;
        
        private string exportPathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Site {
            get {
                return this.siteField;
            }
            set {
                this.siteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ExportPath {
            get {
                return this.exportPathField;
            }
            set {
                this.exportPathField = value;
            }
        }
    }
}
