//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Squint {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class SquintProtocol {
        
        private byte protocolIDField;
        
        private byte versionField;
        
        private SquintProtocolProtocolMetaData protocolMetaDataField;
        
        private SquintProtocolIntent[] treatmentIntentsField;
        
        private SquintProtocolStructure[] structuresField;
        
        private SquintProtocolProtocolChecklist protocolChecklistField;
        
        private SquintProtocolComponent[] componentsField;
        
        private SquintProtocolConstraint[] constraintsField;
        
        /// <remarks/>
        public byte ProtocolID {
            get {
                return this.protocolIDField;
            }
            set {
                this.protocolIDField = value;
            }
        }
        
        /// <remarks/>
        public byte version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public SquintProtocolProtocolMetaData ProtocolMetaData {
            get {
                return this.protocolMetaDataField;
            }
            set {
                this.protocolMetaDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Intent", IsNullable=false)]
        public SquintProtocolIntent[] TreatmentIntents {
            get {
                return this.treatmentIntentsField;
            }
            set {
                this.treatmentIntentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Structure", IsNullable=false)]
        public SquintProtocolStructure[] Structures {
            get {
                return this.structuresField;
            }
            set {
                this.structuresField = value;
            }
        }
        
        /// <remarks/>
        public SquintProtocolProtocolChecklist ProtocolChecklist {
            get {
                return this.protocolChecklistField;
            }
            set {
                this.protocolChecklistField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Component", IsNullable=false)]
        public SquintProtocolComponent[] Components {
            get {
                return this.componentsField;
            }
            set {
                this.componentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Constraint", IsNullable=false)]
        public SquintProtocolConstraint[] Constraints {
            get {
                return this.constraintsField;
            }
            set {
                this.constraintsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolProtocolMetaData {
        
        private string protocolNameField;
        
        private string protocolTypeField;
        
        private byte numComponentsField;
        
        private string protocolDateField;
        
        private string authorField;
        
        private string approvalStatusField;
        
        private string diseaseSiteField;
        
        private string treatmentCentreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProtocolName {
            get {
                return this.protocolNameField;
            }
            set {
                this.protocolNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProtocolType {
            get {
                return this.protocolTypeField;
            }
            set {
                this.protocolTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte NumComponents {
            get {
                return this.numComponentsField;
            }
            set {
                this.numComponentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProtocolDate {
            get {
                return this.protocolDateField;
            }
            set {
                this.protocolDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ApprovalStatus {
            get {
                return this.approvalStatusField;
            }
            set {
                this.approvalStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DiseaseSite {
            get {
                return this.diseaseSiteField;
            }
            set {
                this.diseaseSiteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TreatmentCentre {
            get {
                return this.treatmentCentreField;
            }
            set {
                this.treatmentCentreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolIntent {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolStructure {
        
        private SquintProtocolStructureStructureChecklist structureChecklistField;
        
        private SquintProtocolStructureEclipseId[] eclipseAliasesField;
        
        private string labelField;
        
        private string protocolStructureNameField;
        
        /// <remarks/>
        public SquintProtocolStructureStructureChecklist StructureChecklist {
            get {
                return this.structureChecklistField;
            }
            set {
                this.structureChecklistField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("EclipseId", IsNullable=false)]
        public SquintProtocolStructureEclipseId[] EclipseAliases {
            get {
                return this.eclipseAliasesField;
            }
            set {
                this.eclipseAliasesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProtocolStructureName {
            get {
                return this.protocolStructureNameField;
            }
            set {
                this.protocolStructureNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolStructureStructureChecklist {
        
        private SquintProtocolStructureStructureChecklistPointContourCheck pointContourCheckField;
        
        /// <remarks/>
        public SquintProtocolStructureStructureChecklistPointContourCheck PointContourCheck {
            get {
                return this.pointContourCheckField;
            }
            set {
                this.pointContourCheckField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolStructureStructureChecklistPointContourCheck {
        
        private decimal thresholdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Threshold {
            get {
                return this.thresholdField;
            }
            set {
                this.thresholdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolStructureEclipseId {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolProtocolChecklist {
        
        private SquintProtocolProtocolChecklistArtifacts artifactsField;
        
        private SquintProtocolProtocolChecklistSupports supportsField;
        
        private SquintProtocolProtocolChecklistCalculation calculationField;
        
        private SquintProtocolProtocolChecklistSimulation simulationField;
        
        /// <remarks/>
        public SquintProtocolProtocolChecklistArtifacts Artifacts {
            get {
                return this.artifactsField;
            }
            set {
                this.artifactsField = value;
            }
        }
        
        /// <remarks/>
        public SquintProtocolProtocolChecklistSupports Supports {
            get {
                return this.supportsField;
            }
            set {
                this.supportsField = value;
            }
        }
        
        /// <remarks/>
        public SquintProtocolProtocolChecklistCalculation Calculation {
            get {
                return this.calculationField;
            }
            set {
                this.calculationField = value;
            }
        }
        
        /// <remarks/>
        public SquintProtocolProtocolChecklistSimulation Simulation {
            get {
                return this.simulationField;
            }
            set {
                this.simulationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolProtocolChecklistArtifacts {
        
        private SquintProtocolProtocolChecklistArtifactsArtifact artifactField;
        
        /// <remarks/>
        public SquintProtocolProtocolChecklistArtifactsArtifact Artifact {
            get {
                return this.artifactField;
            }
            set {
                this.artifactField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolProtocolChecklistArtifactsArtifact {
        
        private byte huField;
        
        private decimal toleranceHUField;
        
        private string protocolStructureNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte HU {
            get {
                return this.huField;
            }
            set {
                this.huField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ToleranceHU {
            get {
                return this.toleranceHUField;
            }
            set {
                this.toleranceHUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProtocolStructureName {
            get {
                return this.protocolStructureNameField;
            }
            set {
                this.protocolStructureNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolProtocolChecklistSupports {
        
        private short couchSurfaceField;
        
        private bool couchSurfaceFieldSpecified;
        
        private short couchInteriorField;
        
        private bool couchInteriorFieldSpecified;
        
        private string indicationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short CouchSurface {
            get {
                return this.couchSurfaceField;
            }
            set {
                this.couchSurfaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CouchSurfaceSpecified {
            get {
                return this.couchSurfaceFieldSpecified;
            }
            set {
                this.couchSurfaceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short CouchInterior {
            get {
                return this.couchInteriorField;
            }
            set {
                this.couchInteriorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CouchInteriorSpecified {
            get {
                return this.couchInteriorFieldSpecified;
            }
            set {
                this.couchInteriorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Indication {
            get {
                return this.indicationField;
            }
            set {
                this.indicationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolProtocolChecklistCalculation {
        
        private string algorithmField;
        
        private decimal algorithmResolutionField;
        
        private bool algorithmResolutionFieldSpecified;
        
        private bool heterogeneityOnField;
        
        private bool heterogeneityOnFieldSpecified;
        
        private string fieldNormalizationModeField;
        
        private string vMATOptimizationAlgorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal AlgorithmResolution {
            get {
                return this.algorithmResolutionField;
            }
            set {
                this.algorithmResolutionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AlgorithmResolutionSpecified {
            get {
                return this.algorithmResolutionFieldSpecified;
            }
            set {
                this.algorithmResolutionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool HeterogeneityOn {
            get {
                return this.heterogeneityOnField;
            }
            set {
                this.heterogeneityOnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HeterogeneityOnSpecified {
            get {
                return this.heterogeneityOnFieldSpecified;
            }
            set {
                this.heterogeneityOnFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FieldNormalizationMode {
            get {
                return this.fieldNormalizationModeField;
            }
            set {
                this.fieldNormalizationModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VMATOptimizationAlgorithm {
            get {
                return this.vMATOptimizationAlgorithmField;
            }
            set {
                this.vMATOptimizationAlgorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolProtocolChecklistSimulation {
        
        private SquintProtocolProtocolChecklistSimulationCTDeviceIds cTDeviceIdsField;
        
        private decimal sliceSpacingField;
        
        /// <remarks/>
        public SquintProtocolProtocolChecklistSimulationCTDeviceIds CTDeviceIds {
            get {
                return this.cTDeviceIdsField;
            }
            set {
                this.cTDeviceIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal SliceSpacing {
            get {
                return this.sliceSpacingField;
            }
            set {
                this.sliceSpacingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolProtocolChecklistSimulationCTDeviceIds {
        
        private SquintProtocolProtocolChecklistSimulationCTDeviceIdsCTDeviceId cTDeviceIdField;
        
        /// <remarks/>
        public SquintProtocolProtocolChecklistSimulationCTDeviceIdsCTDeviceId CTDeviceId {
            get {
                return this.cTDeviceIdField;
            }
            set {
                this.cTDeviceIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolProtocolChecklistSimulationCTDeviceIdsCTDeviceId {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolComponent {
        
        private SquintProtocolComponentPrescription prescriptionField;
        
        private SquintProtocolComponentImagingProtocol[] imagingProtocolsField;
        
        private SquintProtocolComponentConstituent[] constituentsField;
        
        private SquintProtocolComponentBeam[] beamsField;
        
        private string componentNameField;
        
        private string typeField;
        
        private byte numFractionsField;
        
        private bool numFractionsFieldSpecified;
        
        private ushort referenceDoseField;
        
        private bool referenceDoseFieldSpecified;
        
        private ushort minBeamsField;
        
        private bool minBeamsFieldSpecified;
        
        private ushort minColOffsetField;
        
        private bool minColOffsetFieldSpecified;
        
        private ushort maxBeamsField;
        
        private bool maxBeamsFieldSpecified;
        
        private ushort numIsoField;
        
        private bool numIsoFieldSpecified;
        
        /// <remarks/>
        public SquintProtocolComponentPrescription Prescription {
            get {
                return this.prescriptionField;
            }
            set {
                this.prescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ImagingProtocol", IsNullable=false)]
        public SquintProtocolComponentImagingProtocol[] ImagingProtocols {
            get {
                return this.imagingProtocolsField;
            }
            set {
                this.imagingProtocolsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Constituent", IsNullable=false)]
        public SquintProtocolComponentConstituent[] Constituents {
            get {
                return this.constituentsField;
            }
            set {
                this.constituentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Beam", IsNullable=false)]
        public SquintProtocolComponentBeam[] Beams {
            get {
                return this.beamsField;
            }
            set {
                this.beamsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ComponentName {
            get {
                return this.componentNameField;
            }
            set {
                this.componentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte NumFractions {
            get {
                return this.numFractionsField;
            }
            set {
                this.numFractionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumFractionsSpecified {
            get {
                return this.numFractionsFieldSpecified;
            }
            set {
                this.numFractionsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort ReferenceDose {
            get {
                return this.referenceDoseField;
            }
            set {
                this.referenceDoseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReferenceDoseSpecified {
            get {
                return this.referenceDoseFieldSpecified;
            }
            set {
                this.referenceDoseFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort MinBeams {
            get {
                return this.minBeamsField;
            }
            set {
                this.minBeamsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinBeamsSpecified {
            get {
                return this.minBeamsFieldSpecified;
            }
            set {
                this.minBeamsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort MinColOffset {
            get {
                return this.minColOffsetField;
            }
            set {
                this.minColOffsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinColOffsetSpecified {
            get {
                return this.minColOffsetFieldSpecified;
            }
            set {
                this.minColOffsetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort MaxBeams {
            get {
                return this.maxBeamsField;
            }
            set {
                this.maxBeamsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxBeamsSpecified {
            get {
                return this.maxBeamsFieldSpecified;
            }
            set {
                this.maxBeamsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort NumIso {
            get {
                return this.numIsoField;
            }
            set {
                this.numIsoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumIsoSpecified {
            get {
                return this.numIsoFieldSpecified;
            }
            set {
                this.numIsoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolComponentPrescription {
        
        private byte numFractionsField;
        
        private ushort referenceDoseField;
        
        private byte pNVMinField;
        
        private bool pNVMinFieldSpecified;
        
        private byte pNVMaxField;
        
        private bool pNVMaxFieldSpecified;
        
        private byte prescribedPercentageField;
        
        private bool prescribedPercentageFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte NumFractions {
            get {
                return this.numFractionsField;
            }
            set {
                this.numFractionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort ReferenceDose {
            get {
                return this.referenceDoseField;
            }
            set {
                this.referenceDoseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte PNVMin {
            get {
                return this.pNVMinField;
            }
            set {
                this.pNVMinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PNVMinSpecified {
            get {
                return this.pNVMinFieldSpecified;
            }
            set {
                this.pNVMinFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte PNVMax {
            get {
                return this.pNVMaxField;
            }
            set {
                this.pNVMaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PNVMaxSpecified {
            get {
                return this.pNVMaxFieldSpecified;
            }
            set {
                this.pNVMaxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte PrescribedPercentage {
            get {
                return this.prescribedPercentageField;
            }
            set {
                this.prescribedPercentageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrescribedPercentageSpecified {
            get {
                return this.prescribedPercentageFieldSpecified;
            }
            set {
                this.prescribedPercentageFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolComponentImagingProtocol {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolComponentConstituent {
        
        private string componentNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ComponentName {
            get {
                return this.componentNameField;
            }
            set {
                this.componentNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolComponentBeam {
        
        private object[] itemsField;
        
        private string protocolBeamNameField;
        
        private string techniqueField;
        
        private ushort minMUWarningField;
        
        private bool minMUWarningFieldSpecified;
        
        private ushort maxMUWarningField;
        
        private bool maxMUWarningFieldSpecified;
        
        private byte startAngleField;
        
        private bool startAngleFieldSpecified;
        
        private byte endAngleField;
        
        private bool endAngleFieldSpecified;
        
        private string toleranceTableField;
        
        private byte minColRotationField;
        
        private bool minColRotationFieldSpecified;
        
        private byte couchRotationField;
        
        private bool couchRotationFieldSpecified;
        
        private byte minXField;
        
        private bool minXFieldSpecified;
        
        private byte maxXField;
        
        private bool maxXFieldSpecified;
        
        private byte minYField;
        
        private bool minYFieldSpecified;
        
        private byte maxYField;
        
        private bool maxYFieldSpecified;
        
        private string jawTracking_IndicationField;
        
        private byte maxColRotationField;
        
        private bool maxColRotationFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BolusDefinitions", typeof(SquintProtocolComponentBeamBolusDefinitions))]
        [System.Xml.Serialization.XmlElementAttribute("EclipseAliases", typeof(SquintProtocolComponentBeamEclipseAliases))]
        [System.Xml.Serialization.XmlElementAttribute("ValidEnergies", typeof(SquintProtocolComponentBeamValidEnergies))]
        [System.Xml.Serialization.XmlElementAttribute("ValidGeometries", typeof(SquintProtocolComponentBeamValidGeometries))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProtocolBeamName {
            get {
                return this.protocolBeamNameField;
            }
            set {
                this.protocolBeamNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Technique {
            get {
                return this.techniqueField;
            }
            set {
                this.techniqueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort MinMUWarning {
            get {
                return this.minMUWarningField;
            }
            set {
                this.minMUWarningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinMUWarningSpecified {
            get {
                return this.minMUWarningFieldSpecified;
            }
            set {
                this.minMUWarningFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort MaxMUWarning {
            get {
                return this.maxMUWarningField;
            }
            set {
                this.maxMUWarningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxMUWarningSpecified {
            get {
                return this.maxMUWarningFieldSpecified;
            }
            set {
                this.maxMUWarningFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte StartAngle {
            get {
                return this.startAngleField;
            }
            set {
                this.startAngleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartAngleSpecified {
            get {
                return this.startAngleFieldSpecified;
            }
            set {
                this.startAngleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte EndAngle {
            get {
                return this.endAngleField;
            }
            set {
                this.endAngleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EndAngleSpecified {
            get {
                return this.endAngleFieldSpecified;
            }
            set {
                this.endAngleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ToleranceTable {
            get {
                return this.toleranceTableField;
            }
            set {
                this.toleranceTableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte MinColRotation {
            get {
                return this.minColRotationField;
            }
            set {
                this.minColRotationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinColRotationSpecified {
            get {
                return this.minColRotationFieldSpecified;
            }
            set {
                this.minColRotationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte CouchRotation {
            get {
                return this.couchRotationField;
            }
            set {
                this.couchRotationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CouchRotationSpecified {
            get {
                return this.couchRotationFieldSpecified;
            }
            set {
                this.couchRotationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte MinX {
            get {
                return this.minXField;
            }
            set {
                this.minXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinXSpecified {
            get {
                return this.minXFieldSpecified;
            }
            set {
                this.minXFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte MaxX {
            get {
                return this.maxXField;
            }
            set {
                this.maxXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxXSpecified {
            get {
                return this.maxXFieldSpecified;
            }
            set {
                this.maxXFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte MinY {
            get {
                return this.minYField;
            }
            set {
                this.minYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinYSpecified {
            get {
                return this.minYFieldSpecified;
            }
            set {
                this.minYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte MaxY {
            get {
                return this.maxYField;
            }
            set {
                this.maxYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxYSpecified {
            get {
                return this.maxYFieldSpecified;
            }
            set {
                this.maxYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string JawTracking_Indication {
            get {
                return this.jawTracking_IndicationField;
            }
            set {
                this.jawTracking_IndicationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte MaxColRotation {
            get {
                return this.maxColRotationField;
            }
            set {
                this.maxColRotationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxColRotationSpecified {
            get {
                return this.maxColRotationFieldSpecified;
            }
            set {
                this.maxColRotationFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolComponentBeamBolusDefinitions {
        
        private SquintProtocolComponentBeamBolusDefinitionsBolus bolusField;
        
        /// <remarks/>
        public SquintProtocolComponentBeamBolusDefinitionsBolus Bolus {
            get {
                return this.bolusField;
            }
            set {
                this.bolusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolComponentBeamBolusDefinitionsBolus {
        
        private byte huField;
        
        private bool huFieldSpecified;
        
        private decimal thicknessField;
        
        private bool thicknessFieldSpecified;
        
        private string indicationField;
        
        private decimal toleranceHUField;
        
        private bool toleranceHUFieldSpecified;
        
        private decimal toleranceThicknessField;
        
        private bool toleranceThicknessFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte HU {
            get {
                return this.huField;
            }
            set {
                this.huField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HUSpecified {
            get {
                return this.huFieldSpecified;
            }
            set {
                this.huFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Thickness {
            get {
                return this.thicknessField;
            }
            set {
                this.thicknessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ThicknessSpecified {
            get {
                return this.thicknessFieldSpecified;
            }
            set {
                this.thicknessFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Indication {
            get {
                return this.indicationField;
            }
            set {
                this.indicationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ToleranceHU {
            get {
                return this.toleranceHUField;
            }
            set {
                this.toleranceHUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ToleranceHUSpecified {
            get {
                return this.toleranceHUFieldSpecified;
            }
            set {
                this.toleranceHUFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ToleranceThickness {
            get {
                return this.toleranceThicknessField;
            }
            set {
                this.toleranceThicknessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ToleranceThicknessSpecified {
            get {
                return this.toleranceThicknessFieldSpecified;
            }
            set {
                this.toleranceThicknessFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolComponentBeamEclipseAliases {
        
        private SquintProtocolComponentBeamEclipseAliasesEclipseId[] eclipseIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EclipseId")]
        public SquintProtocolComponentBeamEclipseAliasesEclipseId[] EclipseId {
            get {
                return this.eclipseIdField;
            }
            set {
                this.eclipseIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolComponentBeamEclipseAliasesEclipseId {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolComponentBeamValidEnergies {
        
        private SquintProtocolComponentBeamValidEnergiesEnergy[] energyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Energy")]
        public SquintProtocolComponentBeamValidEnergiesEnergy[] Energy {
            get {
                return this.energyField;
            }
            set {
                this.energyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolComponentBeamValidEnergiesEnergy {
        
        private string modeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolComponentBeamValidGeometries {
        
        private SquintProtocolComponentBeamValidGeometriesGeometry[] geometryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Geometry")]
        public SquintProtocolComponentBeamValidGeometriesGeometry[] Geometry {
            get {
                return this.geometryField;
            }
            set {
                this.geometryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolComponentBeamValidGeometriesGeometry {
        
        private string geometryNameField;
        
        private decimal startAngleField;
        
        private bool startAngleFieldSpecified;
        
        private decimal startAngleToleranceField;
        
        private bool startAngleToleranceFieldSpecified;
        
        private decimal endAngleField;
        
        private bool endAngleFieldSpecified;
        
        private decimal endAngleToleranceField;
        
        private bool endAngleToleranceFieldSpecified;
        
        private string trajectoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string GeometryName {
            get {
                return this.geometryNameField;
            }
            set {
                this.geometryNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal StartAngle {
            get {
                return this.startAngleField;
            }
            set {
                this.startAngleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartAngleSpecified {
            get {
                return this.startAngleFieldSpecified;
            }
            set {
                this.startAngleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal StartAngleTolerance {
            get {
                return this.startAngleToleranceField;
            }
            set {
                this.startAngleToleranceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartAngleToleranceSpecified {
            get {
                return this.startAngleToleranceFieldSpecified;
            }
            set {
                this.startAngleToleranceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal EndAngle {
            get {
                return this.endAngleField;
            }
            set {
                this.endAngleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EndAngleSpecified {
            get {
                return this.endAngleFieldSpecified;
            }
            set {
                this.endAngleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal EndAngleTolerance {
            get {
                return this.endAngleToleranceField;
            }
            set {
                this.endAngleToleranceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EndAngleToleranceSpecified {
            get {
                return this.endAngleToleranceFieldSpecified;
            }
            set {
                this.endAngleToleranceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Trajectory {
            get {
                return this.trajectoryField;
            }
            set {
                this.trajectoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SquintProtocolConstraint {
        
        private string componentNameField;
        
        private string protocolStructureNameField;
        
        private string constraintTypeField;
        
        private decimal constraintValueField;
        
        private string constraintUnitField;
        
        private string referenceTypeField;
        
        private decimal majorViolationField;
        
        private decimal minorViolationField;
        
        private bool minorViolationFieldSpecified;
        
        private string referenceUnitField;
        
        private decimal stopField;
        
        private bool stopFieldSpecified;
        
        private string descriptionField;
        
        private string dataTablePathField;
        
        private string referenceStructureNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ComponentName {
            get {
                return this.componentNameField;
            }
            set {
                this.componentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProtocolStructureName {
            get {
                return this.protocolStructureNameField;
            }
            set {
                this.protocolStructureNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ConstraintType {
            get {
                return this.constraintTypeField;
            }
            set {
                this.constraintTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ConstraintValue {
            get {
                return this.constraintValueField;
            }
            set {
                this.constraintValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ConstraintUnit {
            get {
                return this.constraintUnitField;
            }
            set {
                this.constraintUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReferenceType {
            get {
                return this.referenceTypeField;
            }
            set {
                this.referenceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal MajorViolation {
            get {
                return this.majorViolationField;
            }
            set {
                this.majorViolationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal MinorViolation {
            get {
                return this.minorViolationField;
            }
            set {
                this.minorViolationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinorViolationSpecified {
            get {
                return this.minorViolationFieldSpecified;
            }
            set {
                this.minorViolationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReferenceUnit {
            get {
                return this.referenceUnitField;
            }
            set {
                this.referenceUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Stop {
            get {
                return this.stopField;
            }
            set {
                this.stopField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StopSpecified {
            get {
                return this.stopFieldSpecified;
            }
            set {
                this.stopFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DataTablePath {
            get {
                return this.dataTablePathField;
            }
            set {
                this.dataTablePathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReferenceStructureName {
            get {
                return this.referenceStructureNameField;
            }
            set {
                this.referenceStructureNameField = value;
            }
        }
    }
}
